import nbformat as nbf
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell
import pandas as pd
from typing import Dict, Any
from autoeda_plus.core.data_loader import load_csv, validate_dataset
from autoeda_plus.core.schema_detector import detect_column_types, detect_potential_target, get_column_summary
from autoeda_plus.core.data_profiler import profile_dataset, detect_data_quality_issues
from autoeda_plus.analysis.statistics_engine import compute_numerical_statistics, compute_categorical_statistics
from autoeda_plus.analysis.correlation_engine import compute_correlation_matrix, detect_strong_correlations
from autoeda_plus.analysis.outlier_detector import get_outlier_summary
from autoeda_plus.visualization.plot_engine import (generate_histogram, generate_boxplot, generate_countplot,
                                       generate_correlation_heatmap, generate_scatterplot, generate_missing_values_plot)
from autoeda_plus.ml.baseline_models import train_baseline_model
from autoeda_plus.insights.insight_generator import generate_insights, generate_feature_engineering_suggestions
from autoeda_plus.cleaning.data_cleaner import clean_dataset

def build_comprehensive_eda_notebook(csv_path: str, output_path: str = 'EDA_report.ipynb', *, clean: bool = False, no_plots: bool = False, summary_only: bool = False, cap_outliers: bool = False) -> None:
    """
    Build a comprehensive EDA notebook.

    Args:
        csv_path (str): Path to CSV file.
        output_path (str): Output notebook path.
    """
    # Load and validate data
    df = load_csv(csv_path)
    is_valid, message = validate_dataset(df)
    if not is_valid:
        raise ValueError(message)

    df_name = 'df'

    # Perform all analyses
    column_types = detect_column_types(df)

    cleaned_df = df
    cleaning_report = []
    if clean:
        cleaned_df, cleaning_report = clean_dataset(df, column_types, apply_outlier_capping=cap_outliers)
        # re-detect types after cleaning
        column_types = detect_column_types(cleaned_df)

    profile = profile_dataset(cleaned_df)
    quality_issues = detect_data_quality_issues(cleaned_df, column_types)
    num_stats = compute_numerical_statistics(cleaned_df, column_types)
    cat_stats = compute_categorical_statistics(cleaned_df, column_types)
    corr_matrix = compute_correlation_matrix(cleaned_df, column_types)
    outlier_summary = get_outlier_summary(cleaned_df, column_types)
    target_col = detect_potential_target(cleaned_df, column_types)
    ml_results = train_baseline_model(cleaned_df, target_col, column_types)
    insights = generate_insights(cleaned_df, column_types, corr_matrix, outlier_summary)
    fe_suggestions = generate_feature_engineering_suggestions(column_types, num_stats)

    # Create notebook
    nb = new_notebook()

    # Title
    nb.cells.append(new_markdown_cell("# AutoEDA++: Automated Intelligent Exploratory Data Analysis"))

    # Introduction
    nb.cells.append(new_markdown_cell("## 1. Introduction\n\nThis notebook was automatically generated by AutoEDA++, providing comprehensive exploratory data analysis of your dataset."))

    # Dataset Loading
    nb.cells.append(new_markdown_cell("## 2. Dataset Loading"))
    # Convert backslashes to forward slashes for cross-platform compatibility
    csv_path_forward = csv_path.replace('\\', '/')
    nb.cells.append(new_code_cell(f"""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

# Load dataset with encoding handling
encodings_to_try = ['utf-8', 'latin1', 'cp1252', 'iso-8859-1']
for encoding in encodings_to_try:
    try:
        {df_name} = pd.read_csv('{csv_path_forward}', encoding=encoding, parse_dates=True, low_memory=False)
        print(f'Dataset loaded successfully with encoding: {{encoding}}')
        break
    except (UnicodeDecodeError, UnicodeError):
        continue
else:
    # Fallback
    {df_name} = pd.read_csv('{csv_path_forward}', parse_dates=True, low_memory=False)
    print('Dataset loaded successfully!')
print(f'Shape: {df_name}.shape')"""))

    # Dataset Overview
    nb.cells.append(new_markdown_cell("## 3. Dataset Overview"))
    nb.cells.append(new_code_cell(f"print('First 5 rows:')\n{df_name}.head()"))
    nb.cells.append(new_code_cell(f"print('\\nDataset Info:')\n{df_name}.info()"))
    nb.cells.append(new_code_cell(f"print('\\nBasic Statistics:')\n{df_name}.describe(include='all')"))

    # Data Cleaning Report (if applied)
    if clean:
        nb.cells.append(new_markdown_cell("## 3. Data Cleaning Report"))
        if cleaning_report:
            for line in cleaning_report:
                nb.cells.append(new_markdown_cell(line))
        else:
            nb.cells.append(new_markdown_cell("No cleaning actions performed."))
        # Add a code cell that performs the same cleaning steps inside the notebook
        cleaning_code_lines = []
        cleaning_code_lines.append("# Apply automatic cleaning steps (mirrors offline cleaning)")
        cleaning_code_lines.append("df = df.copy()")
        cleaning_code_lines.append("# 1) remove duplicates")
        cleaning_code_lines.append("df = df.drop_duplicates()")
        cleaning_code_lines.append("# 2) detect identifier-like columns and drop them")
        cleaning_code_lines.append("n = len(df)")
        cleaning_code_lines.append("ids = [c for c in df.columns if n>0 and df[c].nunique(dropna=False)/n >= 0.98]")
        cleaning_code_lines.append("if ids:")
        cleaning_code_lines.append("    print('Dropping identifier columns:', ids)")
        cleaning_code_lines.append("    df = df.drop(columns=ids)")
        cleaning_code_lines.append("# 3) missing value handling: numeric->median, categorical->mode; drop cols >40% missing")
        cleaning_code_lines.append("for c in list(df.columns):")
        cleaning_code_lines.append("    miss = df[c].isna().sum(); frac = miss/len(df) if len(df)>0 else 0")
        cleaning_code_lines.append("    if frac > 0.4:")
        cleaning_code_lines.append("        print(f'Dropping {c} due to high missing fraction {frac:.2%}')")
        cleaning_code_lines.append("        df.drop(columns=[c], inplace=True)")
        cleaning_code_lines.append("        continue")
        cleaning_code_lines.append("    if miss>0:")
        cleaning_code_lines.append("        if pd.api.types.is_numeric_dtype(df[c]):")
        cleaning_code_lines.append("            df[c] = df[c].fillna(df[c].median())")
        cleaning_code_lines.append("        else:")
        cleaning_code_lines.append("            mode = df[c].mode(); df[c] = df[c].fillna(mode.iloc[0] if not mode.empty else 'Unknown')")
        cleaning_code_lines.append("# 4) convert numeric strings and datetimes where possible")
        cleaning_code_lines.append("for c in df.select_dtypes(include=['object']).columns:")
        cleaning_code_lines.append("    try:")
        cleaning_code_lines.append("        df[c] = pd.to_numeric(df[c], errors='raise')")
        cleaning_code_lines.append("        print(f'Converted {c} to numeric')")
        cleaning_code_lines.append("        continue")
        cleaning_code_lines.append("    except Exception:")
        cleaning_code_lines.append("        pass")
        cleaning_code_lines.append("    try:")
        cleaning_code_lines.append("        df[c] = pd.to_datetime(df[c], errors='raise')")
        cleaning_code_lines.append("        print(f'Converted {c} to datetime')")
        cleaning_code_lines.append("    except Exception:")
        cleaning_code_lines.append("        pass")
        cleaning_code_lines.append("# 5) standardize categoricals")
        cleaning_code_lines.append("for c in df.select_dtypes(include=['object']).columns:")
        cleaning_code_lines.append("    df[c] = df[c].astype(str).str.strip().str.lower()")
        if cap_outliers:
            cleaning_code_lines.append("# 6) cap outliers using IQR for numeric columns")
            cleaning_code_lines.append("for c in df.select_dtypes(include=['number']).columns:")
            cleaning_code_lines.append("    Q1 = df[c].quantile(0.25); Q3 = df[c].quantile(0.75); IQR = Q3-Q1")
            cleaning_code_lines.append("    lower = Q1-1.5*IQR; upper = Q3+1.5*IQR")
            cleaning_code_lines.append("    df[c] = df[c].clip(lower, upper)")
        nb.cells.append(new_code_cell('\n'.join(cleaning_code_lines)))

    # Data Quality Analysis
    nb.cells.append(new_markdown_cell("## 4. Data Quality Analysis"))
    if quality_issues:
        issues_text = "\\n".join(quality_issues)
        nb.cells.append(new_markdown_cell(f"### Issues Found:\n{issues_text}"))
    else:
        nb.cells.append(new_markdown_cell("### No major data quality issues detected."))

    nb.cells.append(new_code_cell(generate_missing_values_plot(df)))

    # Column Type Analysis
    nb.cells.append(new_markdown_cell("## 5. Column Type Analysis"))
    summary = get_column_summary(df, column_types)
    for ctype, info in summary.items():
        if info['count'] > 0:
            nb.cells.append(new_markdown_cell(f"### {ctype.title()} Columns ({info['count']})"))
            nb.cells.append(new_markdown_cell(f"Columns: {', '.join(info['columns'])}"))

    # Feature Distributions
    nb.cells.append(new_markdown_cell("## 6. Feature Distributions"))

    # Datetime Analysis
    datetime_cols = [col for col, t in column_types.items() if t == 'datetime']
    if datetime_cols:
        nb.cells.append(new_markdown_cell("### Datetime Features"))
        for col in datetime_cols:  # Show all datetime columns
            nb.cells.append(new_code_cell(f"print('Datetime column: {col}')\nprint({df_name}['{col}'].describe())\n\n# Year distribution\n{df_name}['{col}'].dt.year.value_counts().sort_index().plot(kind='bar')\nplt.title('Distribution by Year - {col}')\nplt.xlabel('Year')\nplt.ylabel('Count')\nplt.show()\n\n# Month distribution\n{df_name}['{col}'].dt.month.value_counts().sort_index().plot(kind='bar')\nplt.title('Distribution by Month - {col}')\nplt.xlabel('Month')\nplt.ylabel('Count')\nplt.show()"))

    # Numerical distributions
    num_cols = [col for col, t in column_types.items() if t == 'numerical']
    if num_cols:
        nb.cells.append(new_markdown_cell("### Numerical Features"))
        for col in num_cols:  # Show all numerical columns
            nb.cells.append(new_code_cell(generate_histogram(df, col)))
            nb.cells.append(new_code_cell(generate_boxplot(df, col)))

    # Categorical distributions
    cat_cols = [col for col, t in column_types.items() if t == 'categorical']
    if cat_cols:
        nb.cells.append(new_markdown_cell("### Categorical Features"))
        for col in cat_cols:  # Show all categorical columns
            nb.cells.append(new_code_cell(generate_countplot(df, col)))

    # Correlation Analysis
    if not corr_matrix.empty:
        nb.cells.append(new_markdown_cell("## 7. Correlation Analysis"))
        nb.cells.append(new_code_cell(f"corr_matrix = {df_name}.select_dtypes(include=[np.number]).corr()\nprint('Correlation Matrix:')\ncorr_matrix"))
        nb.cells.append(new_code_cell(generate_correlation_heatmap(corr_matrix)))

        # Strong correlations
        strong_corrs = detect_strong_correlations(corr_matrix, 0.7)
        if strong_corrs:
            corr_text = "\\n".join([f"- {col1} ↔ {col2}: {corr:.2f}" for col1, col2, corr in strong_corrs])
            nb.cells.append(new_markdown_cell(f"### Strong Correlations (|ρ| ≥ 0.7):\n{corr_text}"))

    # Outlier Detection
    nb.cells.append(new_markdown_cell("## 8. Outlier Detection"))
    outlier_text = []
    for col, counts in outlier_summary.items():
        iqr_count = counts['iqr_outliers']
        z_count = counts['zscore_outliers']
        if iqr_count > 0 or z_count > 0:
            outlier_text.append(f"- {col}: IQR method: {iqr_count}, Z-score method: {z_count}")

    if outlier_text:
        nb.cells.append(new_markdown_cell("\\n".join(outlier_text)))
    else:
        nb.cells.append(new_markdown_cell("No significant outliers detected."))

    # Feature Engineering Suggestions
    nb.cells.append(new_markdown_cell("## 9. Feature Engineering Suggestions"))
    if fe_suggestions:
        suggestions_text = "\\n".join(f"- {s}" for s in fe_suggestions)
        nb.cells.append(new_markdown_cell(suggestions_text))
    else:
        nb.cells.append(new_markdown_cell("No specific feature engineering suggestions at this time."))

    # Baseline Machine Learning (only if successful)
    if ml_results['success']:
        nb.cells.append(new_markdown_cell("## 10. Baseline Machine Learning Model"))
        problem_type = ml_results['problem_type']
        model_name = ml_results['model']
        metrics = ml_results['metrics']

        nb.cells.append(new_markdown_cell(f"### Problem Type: {problem_type.title()}"))
        nb.cells.append(new_markdown_cell(f"### Model: {model_name}"))
        nb.cells.append(new_markdown_cell(f"### Target Column: {target_col}"))

        metrics_text = "\\n".join(f"- {k}: {v:.4f}" for k, v in metrics.items())
        nb.cells.append(new_markdown_cell(f"### Performance Metrics:\n{metrics_text}"))

        # Feature importance
        if 'feature_importance' in ml_results:
            fi = ml_results['feature_importance']
            fi_sorted = sorted(fi.items(), key=lambda x: x[1], reverse=True)[:5]
            fi_text = "\\n".join(f"- {col}: {imp:.4f}" for col, imp in fi_sorted)
            nb.cells.append(new_markdown_cell(f"### Top 5 Feature Importances:\n{fi_text}"))

    # Key Insights Summary
    nb.cells.append(new_markdown_cell("## 10. Key Insights Summary"))
    if insights:
        insights_text = "\\n".join(f"- {insight}" for insight in insights)
        nb.cells.append(new_markdown_cell(insights_text))
    else:
        nb.cells.append(new_markdown_cell("No specific insights generated."))

    # Write notebook
    with open(output_path, 'w', encoding='utf-8') as f:
        nbf.write(nb, f)