"""
AutoEDA++ — Kaggle-Perfect Sensor Feature Engineering
======================================================
Creates temporal, rolling, lag, and statistical features.
Fulfills competition requirements for "Sudden Change" and "Datetime Extraction".
"""
import pandas as pd
import numpy as np
from typing import List, Optional, Dict, Any

# ─────────────────────────────────────────────────────────────────────────────
def extract_datetime_features(df: pd.DataFrame, date_col: Optional[str] = None) -> pd.DataFrame:
    """
    Extracts Hour, Day, Month, and Weekday from any datetime-like column.
    As requested in Section 4 of the competition brief.
    """
    df = df.copy()
    
    # Auto-detect Date column if not provided
    if date_col is None:
        objs = df.select_dtypes(include=['object']).columns
        for c in objs:
            if 'date' in c.lower() or 'time' in c.lower() or 'timestamp' in c.lower():
                date_col = c
                break
        if date_col is None:
            # Fallback to the first object column that might be a date
            dt_cols = df.select_dtypes(include=['datetime64']).columns
            if not dt_cols.empty:
                date_col = dt_cols[0]

    if date_col and date_col in df.columns:
        try:
            # Convert to datetime if not already
            if not pd.api.types.is_datetime64_any_dtype(df[date_col]):
                df[date_col] = pd.to_datetime(df[date_col], errors='coerce')
            
            # Extract features
            prefix = str(date_col)
            df[f"{prefix}_hour"]    = df[date_col].dt.hour
            df[f"{prefix}_day"]     = df[date_col].dt.day
            df[f"{prefix}_month"]   = df[date_col].dt.month
            df[f"{prefix}_weekday"] = df[date_col].dt.weekday
            
            # Drop the original Date column as it's now redundant for most ML models
            # but we keep it for now if requested, the FeaturePipeline will drop it later.
        except Exception:
            pass # Silent failure if column isn't a date
            
    return df


# ─────────────────────────────────────────────────────────────────────────────
def engineer_sensor_features(
    df: pd.DataFrame,
    numeric_cols: Optional[List[str]] = None,
    window: int = 5,
    lag_steps: int = 2,
    drop_original: bool = False,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Engineer rich sensor features for anomaly detection.
    Fulfills Section 5 of the competition brief: Lag, Rolling Stats, and Differences.
    """
    df = df.copy()

    # 1. Datetime extraction (Kaggle Section 4)
    df = extract_datetime_features(df)

    if numeric_cols is None:
        numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
        exclude = {"anomaly", "label", "target", "id", "index", "_hour", "_day", "_month", "_weekday"}
        numeric_cols = [c for c in numeric_cols if not any(ex in c.lower() for ex in exclude)]

    new_cols: List[str] = []

    for col in numeric_cols:
        if col not in df.columns:
            continue

        series = df[col]

        # ── Rolling statistics (Kaggle Section 5) ─────────────────────────────
        rm_col = f"{col}_rolling_mean_{window}"
        rs_col = f"{col}_rolling_std_{window}"
        df[rm_col] = series.rolling(window=window, min_periods=1).mean()
        df[rs_col] = series.rolling(window=window, min_periods=1).std().fillna(0)
        new_cols += [rm_col, rs_col]

        # ── Lag features (Kaggle Section 5) ───────────────────────────────────
        for lag in range(1, lag_steps + 1):
            lag_col = f"{col}_lag_{lag}"
            df[lag_col] = series.shift(lag)
            new_cols.append(lag_col)

        # ── Difference features (Kaggle Section 5: "Sudden Changes") ──────────
        df_col = f"{col}_diff"
        df[df_col] = series.diff() # Standard difference (X_t - X_{t-1})
        new_cols.append(df_col)

        # ── Rate of change (%) ───────────────────────────────────────────────
        roc_col = f"{col}_rate_of_change"
        df[roc_col] = series.pct_change() * 100
        new_cols.append(roc_col)

        # ── Z-score normalisation ─────────────────────────────────────────────
        mean_val, std_val = series.mean(), series.std()
        if std_val > 0:
            z_col = f"{col}_zscore"
            df[z_col] = (series - mean_val) / std_val
            new_cols.append(z_col)

    # Fill NaN created by shifts / rolling on first rows
    # replaced any Inf generated by rate_of_change on zero values
    df = df.replace([np.inf, -np.inf], np.nan)
    for c in new_cols:
        if df[c].dtype in [np.float32, np.float64, np.int32, np.int64]:
            df[c] = df[c].fillna(df[c].median() if df[c].notna().any() else 0)

    if drop_original:
        df.drop(columns=numeric_cols, inplace=True)

    if verbose:
        print(f"\n[FE] 🏷️  Kaggle-Perfect Engineering complete")
        print(f"     ↳ Final shape    : {df.shape}")

    return df


# ─────────────────────────────────────────────────────────────────────────────
def get_feature_engineering_summary(
    original_cols: List[str],
    engineered_df: pd.DataFrame,
) -> Dict[str, Any]:
    """Return a summary dict describing what was engineered."""
    new_cols = [c for c in engineered_df.columns if c not in original_cols]
    groups: Dict[str, List[str]] = {
        "rolling_mean": [], "rolling_std": [], "lag": [], "diff": [], "rate_of_change": [], "zscore": [], "date_": [],
    }
    for c in new_cols:
        for key in groups:
            if key in c:
                groups[key].append(c)
                break

    return {
        "original_column_count": len(original_cols),
        "engineered_column_count": len(new_cols),
        "total_columns": len(engineered_df.columns),
        "feature_groups": groups,
        "new_feature_names": new_cols,
    }


# ─────────────────────────────────────────────────────────────────────────────
def scale_features(df: pd.DataFrame, exclude_cols: Optional[List[str]] = None) -> pd.DataFrame:
    """Min-Max scale all numeric columns (0–1 range)."""
    df = df.copy()
    exclude = set(exclude_cols or [])
    num_cols = df.select_dtypes(include=np.number).columns.tolist()
    for col in num_cols:
        if col in exclude: continue
        col_min, col_max = df[col].min(), df[col].max()
        if col_max != col_min:
            df[col] = (df[col] - col_min) / (col_max - col_min)
    return df
