import nbformat as nbf
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell
import pandas as pd
from core.data_loader import load_csv
from core.feature_detector import detect_data_types, detect_missing_values, detect_duplicates, get_dataset_shape
from core.eda_analyzer import generate_descriptive_stats, analyze_numerical_features, analyze_categorical_features, detect_datetime_features, calculate_correlations, detect_outliers_iqr
from visualization.plot_generator import generate_histogram, generate_boxplot, generate_bar_chart, generate_correlation_heatmap, generate_pairplot

def build_eda_notebook(csv_path: str, output_path: str = 'EDA_notebook.ipynb') -> None:
    """
    Build a Jupyter Notebook for EDA.

    Args:
        csv_path (str): Path to CSV file.
        output_path (str): Output notebook path.
    """
    # Load data
    df = load_csv(csv_path)
    df_name = 'df'

    # Create notebook
    nb = new_notebook()

    # Title
    nb.cells.append(new_markdown_cell("# Automated Exploratory Data Analysis (EDA)"))

    # Dataset Overview
    nb.cells.append(new_markdown_cell("## 1. Dataset Overview"))
    nb.cells.append(new_code_cell(f"import pandas as pd\n{df_name} = pd.read_csv('{csv_path}')"))
    nb.cells.append(new_code_cell(f"print('Dataset Shape:', {df_name}.shape)"))
    nb.cells.append(new_code_cell(f"{df_name}.head()"))

    # Data Structure Inspection
    nb.cells.append(new_markdown_cell("## 2. Data Structure Inspection"))
    nb.cells.append(new_code_cell(f"print('Data Types:')\n{df_name}.dtypes"))
    nb.cells.append(new_code_cell(f"print('Missing Values:')\n{df_name}.isnull().sum()"))
    nb.cells.append(new_code_cell(f"print('Duplicate Rows:', {df_name}.duplicated().sum())"))

    # Missing Value Analysis
    nb.cells.append(new_markdown_cell("## 3. Missing Value Analysis"))
    nb.cells.append(new_code_cell(f"import matplotlib.pyplot as plt\nimport seaborn as sns\nplt.figure(figsize=(10,6))\nsns.heatmap({df_name}.isnull(), cbar=False)\nplt.title('Missing Values Heatmap')\nplt.show()"))

    # Numerical Feature Analysis
    numerical_cols = df.select_dtypes(include=[float, int]).columns.tolist()
    if numerical_cols:
        nb.cells.append(new_markdown_cell("## 4. Numerical Feature Analysis"))
        nb.cells.append(new_code_cell(f"{df_name}.describe()"))
        for col in numerical_cols[:3]:  # Limit to first 3 for brevity
            nb.cells.append(new_code_cell(generate_histogram(df, col)))
            nb.cells.append(new_code_cell(generate_boxplot(df, col)))

    # Categorical Feature Analysis
    categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
    if categorical_cols:
        nb.cells.append(new_markdown_cell("## 5. Categorical Feature Analysis"))
        for col in categorical_cols[:3]:  # Limit to first 3
            nb.cells.append(new_code_cell(generate_bar_chart(df, col)))

    # Correlation Analysis
    if len(numerical_cols) > 1:
        nb.cells.append(new_markdown_cell("## 6. Correlation Analysis"))
        nb.cells.append(new_code_cell(f"numerical_df = {df_name}.select_dtypes(include=['number'])\ncorr_matrix = numerical_df.corr()"))
        nb.cells.append(new_code_cell(generate_correlation_heatmap(None)))
        nb.cells.append(new_code_cell(f"numerical_cols = {numerical_cols}\n" + generate_pairplot(df)))

    # Outlier Detection
    nb.cells.append(new_markdown_cell("## 7. Outlier Detection"))
    for col in numerical_cols[:3]:
        nb.cells.append(new_code_cell(f"outliers = ({df_name}['{col}'] < {df_name}['{col}'].quantile(0.25) - 1.5 * ({df_name}['{col}'].quantile(0.75) - {df_name}['{col}'].quantile(0.25))) | ({df_name}['{col}'] > {df_name}['{col}'].quantile(0.75) + 1.5 * ({df_name}['{col}'].quantile(0.75) - {df_name}['{col}'].quantile(0.25)))\nprint('Outliers in {col}:', outliers.sum())"))

    # Summary Insights
    nb.cells.append(new_markdown_cell("## 8. Summary Insights"))
    nb.cells.append(new_markdown_cell("This notebook was automatically generated by AutoEDA."))

    # Write notebook
    with open(output_path, 'w') as f:
        nbf.write(nb, f)